apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/cloud-native-garage-method-cohort/chuying-james-buildah
    - name: image-repo
      value: quay.io/chuuuing/express-sample-app
  pipelineRef:
    name: nodejs
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
          accessModes:
              - ReadWriteOnce